#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Framework
#
VERSION = 0.1
PACKAGE_NAME = XCode
FRAMEWORK_NAME = XCode

#
# Resource files
#
XCode_RESOURCE_FILES = \
Resources/Version \

#
# Header files
#
XCode_HEADER_FILES = \
GSXCBuildContext.h \
GSXCCommon.h \
NSArray+Additions.h \
NSString+PBXAdditions.h \
PBXAbstractBuildPhase.h \
PBXAbstractTarget.h \
PBXApplicationTarget.h \
PBXAggregateTarget.h \
PBXBuildFile.h \
PBXBuildRule.h \
PBXBundleTarget.h \
PBXCoder.h \
PBXCommon.h \
PBXContainer.h \
PBXContainerItemProxy.h \
PBXCopyFilesBuildPhase.h \
PBXFileReference.h \
PBXFrameworksBuildPhase.h \
PBXFrameworkTarget.h \
PBXGroup.h \
PBXHeadersBuildPhase.h \
PBXNativeTarget.h \
PBXProject.h \
PBXReferenceProxy.h \
PBXResourcesBuildPhase.h \
PBXRezBuildPhase.h \
PBXShellScriptBuildPhase.h \
PBXSourcesBuildPhase.h \
PBXTargetDependency.h \
PBXVariantGroup.h \
XCBuildConfiguration.h \
XCConfigurationList.h \
XCVersionGroup.h 

#
# Class files
#
XCode_OBJC_FILES = \
GSXCBuildContext.m \
NSArray+Additions.m \
NSString+PBXAdditions.m \
PBXAbstractBuildPhase.m \
PBXAbstractTarget.m \
PBXApplicationTarget.m \
PBXAggregateTarget.m \
PBXBuildFile.m \
PBXBuildRule.m \
PBXBundleTarget.m \
PBXCoder.m \
PBXCommon.m \
PBXContainerItemProxy.m \
PBXContainer.m \
PBXCopyFilesBuildPhase.m \
PBXFileReference.m \
PBXFrameworksBuildPhase.m \
PBXFrameworkTarget.m \
PBXGroup.m \
PBXHeadersBuildPhase.m \
PBXNativeTarget.m \
PBXProject.m \
PBXReferenceProxy.m \
PBXResourcesBuildPhase.m \
PBXRezBuildPhase.m \
PBXShellScriptBuildPhase.m \
PBXSourcesBuildPhase.m \
PBXTargetDependency.m \
PBXVariantGroup.m \
XCBuildConfiguration.m \
XCConfigurationList.m \
XCVersionGroup.m

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
