# Makefile for GNUmakefile generation

include $(GNUSTEP_MAKEFILES)/common.make

ADDITIONAL_INCLUDE_DIRS += -I../..
BUNDLE_NAME = ProjectCenter
BUNDLE_EXTENSION = .generator
ProjectCenter_PRINCIPAL_CLASS = 

ProjectCenter_HAS_RESOURCE_BUNDLE = yes

ProjectCenter_OBJC_FILES = 

ProjectCenter_RESOURCE_FILES =

ProjectCenter_STANDARD_INSTALL = yes

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
